birthdate=int(input("Enter your birthdate"))
if(birthdate<7)
  print("to low")
elif(birthdate<15)
  print("close but far")
elif(birthdate<25)
  print("on the tip of your tounge")
elif(birthdate<31)
  print("close but far")
else(birthdate=24)
  print("WELL DONE YOU DID IT!")
